"""add_nps_score_to_risk_scores

Revision ID: 231b91b40cde
Revises: b5899659331f
Create Date: 2026-01-29 18:49:57.063169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '231b91b40cde'
down_revision: Union[str, None] = 'b5899659331f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('risk_scores', sa.Column('nps_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('risk_scores', 'nps_score')
    # ### end Alembic commands ###
