"""create_triggers_tables

Revision ID: 29a9a4df82d5
Revises: 944b3eda5990
Create Date: 2026-01-29 18:13:52.024517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29a9a4df82d5'
down_revision: Union[str, None] = '944b3eda5990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_executions_id'), 'trigger_executions', ['id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_student_id'), 'trigger_executions', ['student_id'], unique=False)
    op.create_index(op.f('ix_trigger_executions_trigger_id'), 'trigger_executions', ['trigger_id'], unique=False)
    op.create_table('triggers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition_type', sa.Enum('DAYS_WITHOUT_ACCESS', 'PROGRESS_BELOW', 'GRADE_BELOW', 'RISK_LEVEL', 'OVERDUE_DAYS', name='triggerconditiontype'), nullable=False),
    sa.Column('condition_value', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.Enum('SEND_WHATSAPP', 'SEND_EMAIL', 'CREATE_TICKET', 'NOTIFY_TEAM', name='triggeractiontype'), nullable=False),
    sa.Column('action_template', sa.Text(), nullable=True),
    sa.Column('cooldown_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_triggers_id'), 'triggers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_triggers_id'), table_name='triggers')
    op.drop_table('triggers')
    op.drop_index(op.f('ix_trigger_executions_trigger_id'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_student_id'), table_name='trigger_executions')
    op.drop_index(op.f('ix_trigger_executions_id'), table_name='trigger_executions')
    op.drop_table('trigger_executions')
    # ### end Alembic commands ###
