"""add_asaas_fields_to_students

Revision ID: 9d7b7afbef50
Revises: 7a936c356671
Create Date: 2026-02-02 14:51:58.534894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7b7afbef50'
down_revision: Union[str, None] = '7a936c356671'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('asaas_customer_id', sa.String(length=100), nullable=True))
    op.add_column('students', sa.Column('financial_status', sa.String(length=20), nullable=True))
    op.add_column('students', sa.Column('overdue_value', sa.Float(), nullable=True))
    op.create_index(op.f('ix_students_asaas_customer_id'), 'students', ['asaas_customer_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_asaas_customer_id'), table_name='students')
    op.drop_column('students', 'overdue_value')
    op.drop_column('students', 'financial_status')
    op.drop_column('students', 'asaas_customer_id')
    # ### end Alembic commands ###
