"""create_moodle_signals_table

Revision ID: ab3b8cc79a4a
Revises: 2600a4fcf6ac
Create Date: 2026-01-28 23:53:26.338832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3b8cc79a4a'
down_revision: Union[str, None] = '2600a4fcf6ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moodle_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('moodle_user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('total_activities', sa.Integer(), nullable=True),
    sa.Column('completed_activities', sa.Integer(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=True),
    sa.Column('course_grade', sa.Float(), nullable=True),
    sa.Column('last_access', sa.DateTime(), nullable=True),
    sa.Column('days_since_access', sa.Integer(), nullable=True),
    sa.Column('captured_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_moodle_signals_course_id'), 'moodle_signals', ['course_id'], unique=False)
    op.create_index(op.f('ix_moodle_signals_id'), 'moodle_signals', ['id'], unique=False)
    op.create_index(op.f('ix_moodle_signals_moodle_user_id'), 'moodle_signals', ['moodle_user_id'], unique=False)
    op.create_index(op.f('ix_moodle_signals_student_id'), 'moodle_signals', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moodle_signals_student_id'), table_name='moodle_signals')
    op.drop_index(op.f('ix_moodle_signals_moodle_user_id'), table_name='moodle_signals')
    op.drop_index(op.f('ix_moodle_signals_id'), table_name='moodle_signals')
    op.drop_index(op.f('ix_moodle_signals_course_id'), table_name='moodle_signals')
    op.drop_table('moodle_signals')
    # ### end Alembic commands ###
