"""create_students_table

Revision ID: f5cafd267a34
Revises: 26c1e443f9b4
Create Date: 2026-01-27 23:38:41.642123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5cafd267a34'
down_revision: Union[str, None] = '26c1e443f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('moodle_user_id', sa.Integer(), nullable=True),
    sa.Column('conta_azul_customer_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_azul_customer_id')
    )
    op.create_index(op.f('ix_students_cpf'), 'students', ['cpf'], unique=True)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_index(op.f('ix_students_moodle_user_id'), 'students', ['moodle_user_id'], unique=True)
    op.create_index(op.f('ix_students_phone'), 'students', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_phone'), table_name='students')
    op.drop_index(op.f('ix_students_moodle_user_id'), table_name='students')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_cpf'), table_name='students')
    op.drop_table('students')
    # ### end Alembic commands ###
